# spring.application.name=commx
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/commx_db
spring.datasource.username=postgres
spring.datasource.password=test123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080